services:
  # nagiyu:
  #   build:
  #     context: ./nagiyu
  #     dockerfile: Dockerfile
  #   container_name: "${PROJECT_NAME}_web"
  #   ports:
  #     - "9019:8080"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  #   volumes:
  #     - ./nagiyu/bin:/app

  localstack:
    build:
      context: ./aws
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}_localstack"
    ports:
      - "9020:4566" # LocalStackのメインエンドポイント
    environment:
      - SERVICES=dynamodb
      - DEBUG=1               # デバッグログをON
